CREATE TABLE IF NOT EXISTS led_groups(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));
CREATE TABLE IF NOT EXISTS calendar(id INT AUTO_INCREMENT PRIMARY KEY, modul INT, start DATETIME, end DATETIME);
